name: Build APK

on:

push:

branches: [ "main" ]

jobs:

build:

runs-on: ubuntu-latest

steps:

- name: Checkout code

uses: actions/checkout@v4

- name: Set up JDK 17

uses: actions/setup-java@v4

with:

java-version: '17'

distribution: 'temurin'

- name: Grant execute permission for gradlew

run: chmod +x gradlew

- name: Build APK with Gradle (Fix Java 8 conflict)

run: |

./gradlew app_pojavlauncher:assembleDebug -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=512m -Xmx2g"
